### ISSUE TITLE
Complete Tests for Ease.ts

### ISSUE THREAD

**Issue by jtenner** [senpai-js/senpai-stage#10]
- [x] Each ease function should return 0 when input is 0
- [x] Each ease function should return 1 when input is 1
- [x] Each provided ease should be continuous

**Comment by yongfei25** [comment]
Hi, first-time contributor here :). Could you describe a bit more on the third item?

**Comment by jtenner** [comment]
Absolutely! These functions reside in the `src/ease/index.ts` typescript file.

If you look [here](https://github.com/danro/jquery-easing/blob/master/jquery.easing.js), these functions are more complicated, but they provide the same functionality, only scaled.

```ts
export type EaseFunc = (ratio: number) => number;
```
So each ease function takes a ratio, and then returns another ratio. For example, a quadratic easeOut could look like this:

```ts
const completedRatio: number = easeInQuad(0.5); // the animation is halfway completed
console.log(completedRatio);
// 0.25 -> However, the resulting animation has moved only 25% of the way
```

We just need to write a test that asserts the following thing about each function:

```ts
const result = ease(0);
expect(result).toBe(0);
// and
const result2 = ease(1);
expect(result).toBe(1);
```

Is this clear? I can keep explaining things until it's understood.

**Comment by jtenner** [comment]
On that third item, it's not a required test, but I want to make sure that the functions are mathematically continuous. It's likely that they are because the functions themselves are composed, and return continuous values, but I would love to actually confirm it in a test.  It's optional.

**Comment by jtenner** [comment]
One final note, it's entirely possible to assert that each `ease` function is strictly increasing.  Perhaps writing a test like this might be useful:

```ts
let previous: number = 0, current: number;
for (let i = 1; i <= 100; i++) {
  number = ease(i * 0.01);
  expect(number).toBeGreaterThan(previous);
  previous = number;
}
```

**Comment by yongfei25** [comment]
Thanks. I've raised a PR for the first and second items. :)

However, I tried adding a test for the third items but  `easeOutElastic`, `easeInElastic`, `easeInOutElastic` would fail because the values are decreasing in a very small value.

**Comment by jtenner** [comment]
Ah! Yes. That does make sense. 

I think using `expect(number).toBeCloseTo(previous, someTestablePrecisionValue)` might be the right thing in this case. Let me do a bit of testing myself with `jest` before I we move forward.

In the meantime, I would be happy to review your pull request.

**Comment by jtenner** [comment]
```
 FAIL  test/TextInput.spec.ts
  ● TextInput behavior › misc test

    expect(received).toBeCloseTo(expected, precision)

    Precision: 2-digit
    Expected: 0.1
    Received: 0.2

      57 |     }
      58 |
    > 59 |     expect(0.2).toBeCloseTo(0.1, 2)
         |                 ^
      60 |   });
      61 | });
      62 |

      at Object.<anonymous> (test/TextInput.spec.ts:59:17)
```

AS you can see here, a value that jumps too quickly will trigger 2 digit precision, probably indicating a non-continuous value.

This test should pass.

```ts
let previous: number = 0
    let current: number;
    for (let i = 1; i < 10000; i++) {
      current = ease(i * 0.0001);
      expect(current).toBeCloseTo(previous, 2);
      previous = current;
    }
```

The test is relatively cheap too, since it doesn't take too long. 

You might also use `Object.entries()` to loop over the exported eases dynamically. Is that possible? I want to always test every exported ease function.

**Comment by jtenner** [comment]
This test works great. Thank you.
